### ISSUE TITLE
AYON custom OTIO exporter gives different results than Hiero native one with image sequences

### ISSUE THREAD

**Issue by robin-ynput** [ynput/ayon-hiero#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Initially reported here: https://github.com/ynput/ayon-core/pull/897#issuecomment-2363067595

AYON native OTIO exporter does not give the same output than Hiero native one (https://learn.foundry.com/hiero/current/content/timeline_environment/exporting/exporting_edls_and_xmls.html).

E.g. for selected Clip:
![image](https://github.com/user-attachments/assets/6498192f-62ac-4115-a0a5-3997b0bde21c)

Source Range
* in Hiero: `00:00:40:00-00:00:44:00` (25fps) == `1000-1100` frames
* in Hiero native OTIO exporter: `otio.opentime.TimeRange(start_time=otio.opentime.RationalTime(value=1000, rate=25), duration=otio.opentime.RationalTime(value=101, rate=25))`
* in AYON custom OTIO exporter: `otio.opentime.TimeRange(start_time=otio.opentime.RationalTime(value=0, rate=25), duration=otio.opentime.RationalTime(value=101, rate=25))`

### Expected Behavior:

AYON custom and Hiero native OTIO exporters should returns similar ranges for clips.

### Version

1.0.0

### What platform you are running on?

Linux / Ubuntu

### Steps To Reproduce:

1. Create a timeline in Hiero from image sequence clips
2. Export as Hiero native
3. Export with AYON exporter
4. Compare exported clips

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by jakubjezek001** [comment]
After some tests, it seems we are facing a similar situation as in Resolve with native OTIO [https://github.com/ynput/ayon-resolve/pull/15](https://github.com/ynput/ayon-resolve/pull/15). The original assumption during AYON's native OTIO development was wrong. The source time should refer to the available range, including the timecode.

This might not be too difficult to fix within each host, but since we use the OTIO file downstream via ayon-core publishing plugins, we should find and fix those issues.

Here is the Hiero testing data.

[testing_sequence_with_mixed_timecodes.zip](https://github.com/user-attachments/files/17112274/testing_sequence_with_mixed_timecodes.zip)
